version: "3"
networks:
  mern-app:
    driver: bridge
services:
  mongo:
    container_name: database_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo_db:/data/db
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6380:6379"
    networks:
      - mern-app
#  cors:
#    build:
#      context: ./nginx
#      dockerfile: Dockerfile
#    container_name: cors_container
#    ports:
#      - "4545:80"
  backend:
#    build: ./backend
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - /usr/challenge-MERN/backend
    #    environment:
    #      PORT: 4000
    #      MONGODB_URI: mongodb://mongo_db:27017
    networks:
      - mern-app
    depends_on:
      - mongo
      - redis
#      - cors
  frontend:
    build: ./frontend
#    network_mode: host
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    networks:
      - mern-app
    depends_on:
      - mongo
      - backend
volumes:
  mongo_db:
    driver: local