name: Backend CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    strategy:
      matrix:
        node-version: [ 18.16]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run Prettier
      run: npm run format:write

#    - name: Check Super Linter
#      uses: github/super-linter@v4
#      env:
#        VALIDATE_ALL_CODEBASE: true
#        VALIDATE_JAVASCRIPT_ES: true
#
#    - name: Lint
#      run: npm run lint:check

    - name: Run test
      run: npm run test
