name: Frontend CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2

    - name: Install dependencies
      run: npm install

    - name: Run Prettier
      run: npm run format

    - name: Check Super Linter
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_JAVASCRIPT_ES: true

    - name: Lint
      run: npm run lint

    - name: Run test
      run: npm run test
